# -----------"ðŸ’² start stats MONAD"|"ðŸ’² Start stats MEGAETH" -----------
THRENDS = 30

LIMIT_REPLACE_PROXY = 10

#sleep time
SLEEP_BEATWEEN_WALLET = [1, 3] # seconds
SLEEP_BEATWEEN_REAPLECE_PROXY = [1, 3] # seconds
#-----------------------------------------------------------
